// Task 165 Phase 2, step 2a: the Edge copy of the ledger engine must stay identical to the web's.
// Spec: docs/agent/specs/discord-holdings.md §2.1 (D6 — the web engine itself is never edited).
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { describe, it, expect } from 'vitest'
import lib from './edgeEngine.cjs'
import * as webEngine from '../../src/utils/pnlEngine.ts'
import * as edgeEngine from '../../supabase/functions/_shared/engine/pnlEngine.ts'
import * as webModels from '../../src/types/models.ts'
import * as edgeModels from '../../supabase/functions/_shared/engine/models.ts'

const { EDGE_ENGINE_FILES, headerFor, renderEdgeFile } = lib
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const read = (rel) => readFileSync(join(ROOT, rel), 'utf8')

const ENGINE = 'src/utils/pnlEngine.ts'
const MODELS = 'src/types/models.ts'

describe('EDGE_ENGINE_FILES', () => {
  it('maps exactly the engine and its model file into _shared/engine', () => {
    expect(EDGE_ENGINE_FILES).toEqual([
      { source: ENGINE, target: 'supabase/functions/_shared/engine/pnlEngine.ts' },
      { source: MODELS, target: 'supabase/functions/_shared/engine/models.ts' },
    ])
  })
})

describe('generated files are current (run `npm run sync:edge-engine` when this fails)', () => {
  for (const { source, target } of [
    { source: ENGINE, target: 'supabase/functions/_shared/engine/pnlEngine.ts' },
    { source: MODELS, target: 'supabase/functions/_shared/engine/models.ts' },
  ]) {
    it(`${target} equals a fresh render of ${source}`, () => {
      expect(read(target)).toBe(renderEdgeFile(source, read(source)))
    })
  }
})

describe('headerFor', () => {
  it('is exactly two comment lines naming the source and the sync command', () => {
    expect(headerFor(ENGINE)).toBe(
      `// GENERATED by scripts/sync-edge-engine.cjs from ${ENGINE} — do not edit.\n` +
        '// Change the source, then run `npm run sync:edge-engine`.\n',
    )
  })
})

describe('renderEdgeFile', () => {
  it('copies models unchanged after the header', () => {
    const text = read(MODELS)
    expect(renderEdgeFile(MODELS, text)).toBe(headerFor(MODELS) + text)
  })

  it('rewrites every models import in the engine to ./models.ts and changes nothing else', () => {
    const text = read(ENGINE)
    const out = renderEdgeFile(ENGINE, text)
    expect(out.startsWith(headerFor(ENGINE))).toBe(true)
    const body = out.slice(headerFor(ENGINE).length)
    expect(body).not.toContain("'../types/models'")
    expect(body.split("from './models.ts'").length - 1).toBe(text.split("from '../types/models'").length - 1)
    expect(body.replaceAll("from './models.ts'", "from '../types/models'")).toBe(text)
  })

  it('throws when the engine has no models import to rewrite', () => {
    expect(() => renderEdgeFile(ENGINE, 'export const x = 1\n')).toThrow()
  })

  it('throws when the engine gains another relative import', () => {
    const text = "import { a } from '../types/models'\nimport { b } from './fees'\n"
    expect(() => renderEdgeFile(ENGINE, text)).toThrow()
  })

  it('throws when the engine gains a relative import with an extension', () => {
    const text = "import { a } from '../types/models'\nimport { b } from '../utils/settings.ts'\n"
    expect(() => renderEdgeFile(ENGINE, text)).toThrow()
  })

  it('throws when the engine source already spells ./models.ts itself', () => {
    const text = "import { a } from '../types/models'\nimport { b } from './models.ts'\n"
    expect(() => renderEdgeFile(ENGINE, text)).toThrow()
  })

  it('throws when the engine gains a bare package import', () => {
    const text = "import { a } from '../types/models'\nimport Decimal from 'decimal.js'\n"
    expect(() => renderEdgeFile(ENGINE, text)).toThrow()
  })

  it('throws when the engine gains a side-effect import', () => {
    const text = "import { a } from '../types/models'\nimport '../polyfill'\n"
    expect(() => renderEdgeFile(ENGINE, text)).toThrow()
  })

  it('throws when the engine gains a dynamic import', () => {
    const text = "import { a } from '../types/models'\nconst m = await import('x')\n"
    expect(() => renderEdgeFile(ENGINE, text)).toThrow()
  })

  it('throws when models gains an import', () => {
    expect(() => renderEdgeFile(MODELS, "import type { X } from './other'\nexport type Y = X\n")).toThrow()
  })

  it('throws for any other source file', () => {
    expect(() => renderEdgeFile('src/utils/fees.ts', 'export const x = 1\n')).toThrow()
  })
})

describe('behavioural parity between the web engine and the Edge copy', () => {
  let seq = 0
  const tx = (input) => {
    seq++
    return {
      id: `tx-${seq}`,
      workspace_id: 'ws-1',
      tx_date: input.date,
      market: input.market,
      ticker: input.ticker,
      name: input.name ?? input.ticker,
      tx_type: input.type,
      price: input.price,
      qty: input.qty,
      fee_tax: input.fee ?? 0,
      tx_nature: input.nature,
      fee_rate: input.feeRate,
      created_at: `2026-01-01T00:00:00.${String(seq).padStart(3, '0')}Z`,
    }
  }

  const fixture = [
    tx({ date: '2025-01-10', market: 'TPE', ticker: '2330', name: '台積電', type: 'BUY', price: 500, qty: 1000, fee: 712 }),
    tx({ date: '2025-03-05', market: 'TPE', ticker: '2330', name: '台積電', type: 'BUY', price: 600, qty: 1000, fee: 855, feeRate: 0.0004275 }),
    tx({ date: '2026-02-01', market: 'TPE', ticker: '2330', name: '台積電', type: 'SELL', price: 700, qty: 500, fee: 1548 }),
    tx({ date: '2026-02-03', market: 'TPE', ticker: '0050', type: 'BUY', price: 150.35, qty: 37, fee: 1 }),
    tx({ date: '2026-02-04', market: 'TPE', ticker: '2317', type: 'BUY', price: 200, qty: 1000, fee: 285, nature: 'DAY_TRADE' }),
    tx({ date: '2026-02-04', market: 'TPE', ticker: '2317', type: 'SELL', price: 205, qty: 1000, fee: 1060, nature: 'DAY_TRADE' }),
    tx({ date: '2026-03-01', market: 'TPE', ticker: '2603', name: '長榮', type: 'SELL', price: 100, qty: 1000, fee: 522, nature: 'SHORT' }),
    tx({ date: '2026-03-20', market: 'TPE', ticker: '2603', name: '長榮', type: 'BUY', price: 95, qty: 400, fee: 54, nature: 'SHORT' }),
    tx({ date: '2025-06-01', market: 'US', ticker: 'AAPL', type: 'BUY', price: 190.12, qty: 3.5, fee: 1 }),
    tx({ date: '2026-01-15', market: 'US', ticker: 'AAPL', type: 'SELL', price: 230.5, qty: 1.25, fee: 1 }),
    tx({ date: '2026-04-01', market: 'TPE', ticker: '9999', type: 'SELL', price: 10, qty: 100, fee: 20 }),
  ]

  it('exports the same runtime names', () => {
    expect(Object.keys(edgeEngine).sort()).toEqual(Object.keys(webEngine).sort())
    expect(Object.keys(edgeModels).sort()).toEqual(Object.keys(webModels).sort())
  })

  it('computeLedger gives identical ledgers, warnings included', () => {
    const web = webEngine.computeLedger(fixture)
    const edge = edgeEngine.computeLedger(fixture)
    expect(web.holdings.length).toBeGreaterThan(0)
    expect(web.warnings.length).toBeGreaterThan(0)
    expect(edge).toEqual(web)
  })

  it('estimateUnrealized and estimateUnrealizedShort agree for every holding', () => {
    const holdings = webEngine.computeLedger(fixture).holdings
    const edgeHoldings = edgeEngine.computeLedger(fixture).holdings
    let shorts = 0
    holdings.forEach((h, i) => {
      for (const [rate, minFee] of [[0.001425, 20], [0.0004275, 1], [0, undefined]]) {
        if (h.qty > 0) {
          expect(edgeEngine.estimateUnrealized(edgeHoldings[i], 123.45, rate, minFee)).toBe(
            webEngine.estimateUnrealized(h, 123.45, rate, minFee),
          )
        }
        if (h.shortQty > 0) {
          shorts++
          expect(edgeEngine.estimateUnrealizedShort(edgeHoldings[i], 98.7, rate, minFee)).toBe(
            webEngine.estimateUnrealizedShort(h, 98.7, rate, minFee),
          )
        }
      }
    })
    expect(shorts).toBeGreaterThan(0)
  })

  it('model helpers agree', () => {
    expect(edgeModels.marketCurrency('TPE')).toBe(webModels.marketCurrency('TPE'))
    expect(edgeModels.marketCurrency('US')).toBe(webModels.marketCurrency('US'))
    expect(edgeModels.positionKey('US', 'AAPL')).toBe(webModels.positionKey('US', 'AAPL'))
  })
})
