/**
 * Task 165 Phase 2 §2.1 — pure renderer that turns the web's ledger engine into an Edge-
 * importable copy. D6 forbids editing `src/utils/pnlEngine.ts` / `src/types/models.ts`, so
 * this module only ever reads them and produces text for `sync-edge-engine.cjs` to write.
 *
 * No network, no filesystem, no I/O of any kind — the same discipline as `snapshotPlan.cjs`.
 */

const ENGINE_SOURCE = 'src/utils/pnlEngine.ts'
const MODELS_SOURCE = 'src/types/models.ts'

const EDGE_ENGINE_FILES = [
  { source: ENGINE_SOURCE, target: 'supabase/functions/_shared/engine/pnlEngine.ts' },
  { source: MODELS_SOURCE, target: 'supabase/functions/_shared/engine/models.ts' },
]

function headerFor(source) {
  return (
    `// GENERATED by scripts/sync-edge-engine.cjs from ${source} — do not edit.\n` +
    '// Change the source, then run `npm run sync:edge-engine`.\n'
  )
}

// Any specifier other than the rewritten './models.ts' (relative or bare package), a side-effect
// import, or a dynamic import() — each would mean the source gained a dependency this generator
// does not carry over, so a stale copy must fail loudly instead of silently shipping to Edge.
const OTHER_IMPORT_RE = /from\s+['"](?!\.\/models\.ts['"])[^'"]*['"]|^\s*import\s+['"]/m
const DYNAMIC_IMPORT_RE = /\bimport\s*\(/

function renderModels(text) {
  if (text.split('\n').some((line) => line.startsWith('import '))) {
    throw new Error(`renderEdgeFile: ${MODELS_SOURCE} must not import anything`)
  }
  return text
}

function renderEngine(text) {
  // './models.ts' must only ever be the product of the rewrite below, never a source spelling.
  if (/['"]\.\/models\.ts['"]/.test(text)) {
    throw new Error(`renderEdgeFile: ${ENGINE_SOURCE} already imports './models.ts'`)
  }
  const rewritten = text.split("from '../types/models'").join("from './models.ts'")
  if (rewritten === text) {
    throw new Error(`renderEdgeFile: ${ENGINE_SOURCE} has no '../types/models' import to rewrite`)
  }
  if (OTHER_IMPORT_RE.test(rewritten)) {
    throw new Error(`renderEdgeFile: ${ENGINE_SOURCE} gained an unexpected import`)
  }
  if (DYNAMIC_IMPORT_RE.test(rewritten)) {
    throw new Error(`renderEdgeFile: ${ENGINE_SOURCE} gained a dynamic import`)
  }
  return rewritten
}

function renderEdgeFile(source, text) {
  let body
  if (source === MODELS_SOURCE) {
    body = renderModels(text)
  } else if (source === ENGINE_SOURCE) {
    body = renderEngine(text)
  } else {
    throw new Error(`renderEdgeFile: unknown source "${source}"`)
  }
  return headerFor(source) + body
}

module.exports = {
  EDGE_ENGINE_FILES,
  headerFor,
  renderEdgeFile,
}
