/**
 * Spec 160 §5 — pure planning core shared by snapshot.cjs and restore.cjs.
 *
 * No network, no filesystem, no I/O of any kind. Everything here is a pure function so the
 * shell scripts can be thin and the risky decisions (which ref may be wiped, whether a
 * placeholder survived substitution) are unit-tested in isolation.
 */

const PROD_REF = 'hrilemueiqyaoiwnkeuu'
const DEV_REF = 'zyebvayngwrqzoaicbwd'

// The six ephemeral auth tables carry no recovery value and must never appear in a snapshot
// (spec §4). Session/token rows would also be stale the moment the dump finishes.
const AUTH_EXCLUDE_TABLES = [
  'auth.audit_log_entries',
  'auth.sessions',
  'auth.refresh_tokens',
  'auth.flow_state',
  'auth.one_time_tokens',
  'auth.saml_relay_states',
]

// Regenerable market-data caches and log tables (Task 160 Phase A-2). Each refills from a
// source API or is append-only telemetry, so a snapshot carries no recovery value for them —
// only the offsite storage cost of copying it daily. `chip_raw_cache` alone was >20 MB of a
// 32 MB DEV snapshot.
const CACHE_TABLES = [
  'public.admin_run_log', // append-only audit trail of admin actions; not needed to restore state
  'public.app_log', // application log lines; regenerated by normal operation
  'public.batch_run_log', // batch job run history; regenerated by the next scheduled run
  'public.chip_raw_cache', // raw market-data cache fetched from source APIs; refills on demand
  'public.price_cache', // price cache fetched from source APIs; refills on demand
  'public.source_probe_log', // source-availability probe history; regenerated by the prober
  'public.source_probe_tick', // source-availability probe ticks; regenerated by the prober
  'public.discord_send_log', // Discord send history; regenerated by the next scheduled send
]

// The webhook URL itself (Task 165 §2.5): must never leave the project in a snapshot, even
// with --with-cache, so it is tracked separately from the regenerable CACHE_TABLES.
const SECRET_TABLES = ['public.app_secrets']

function dataExcludeTables(withCache) {
  return withCache ? SECRET_TABLES : [...CACHE_TABLES, ...SECRET_TABLES]
}

function snapshotDirName(ref, ymd) {
  return `snapshot-${ref}-${ymd}`
}

const SNAPSHOT_DIR_RE = /^snapshot-([a-z0-9]+)-(\d{4}-\d{2}-\d{2})$/

function parseSnapshotDirName(name) {
  const match = SNAPSHOT_DIR_RE.exec(name)
  if (!match) return null
  return { ref: match[1], ymd: match[2] }
}

function buildManifest({ ref, createdAt, encrypted, files }) {
  const sortedFiles = [...files].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
  return { version: 1, ref, createdAt, encrypted, files: sortedFiles }
}

function verifyManifest(manifest, actual) {
  const missing = []
  const mismatched = []
  const seen = new Set()

  for (const file of manifest.files) {
    seen.add(file.path)
    const actualHash = actual[file.path]
    if (actualHash === undefined) {
      missing.push(file.path)
    } else if (actualHash !== file.sha256) {
      mismatched.push(file.path)
    }
  }

  const extra = Object.keys(actual)
    .filter((path) => path !== 'manifest.json' && !seen.has(path))
    .sort()

  const ok = missing.length === 0 && mismatched.length === 0 && extra.length === 0
  return { ok, missing, mismatched, extra }
}

function assertDestructiveTargetAllowed(ref) {
  if (ref !== DEV_REF) {
    throw new Error(`Destructive target refused: "${ref}" is not the DEV ref (${DEV_REF})`)
  }
}

// Builds fresh objects with only the three safe keys. Never spread the input row: a spread
// followed by `delete` would still leak `command` (and the cron secret it carries) if a new
// key is ever added to the source query.
function cronRowsToPlan(rows) {
  return {
    version: 1,
    jobs: rows.map((row) => ({
      jobname: row.jobname,
      schedule: row.schedule,
      action: row.action,
    })),
  }
}

// Narrow: only the two forms that carry a live value in a cron command body. Every other
// occurrence of <PROJECT_REF>/<CRON_SECRET>/<ANON_KEY> (comments, the line-1230 search pattern
// `LIKE '%<PROJECT_REF>%'`) must survive untouched — see spec §3a.
const URL_RE = /https:\/\/<PROJECT_REF>\.supabase\.co/g
// Tolerate variable whitespace after the comma and preserve it in the replacement.
const SECRET_RE = /('x-cron-secret',\s*)'<CRON_SECRET>'/g

function substituteCronPlaceholders(sql, options = {}) {
  const { ref, cronSecret } = options
  // Fail before touching `sql` at all: a missing or blank option must never fall through to
  // `String(undefined)` or an empty substitution silently landing in generated SQL.
  for (const [name, value] of Object.entries({ ref, cronSecret })) {
    if (typeof value !== 'string' || value.trim().length === 0) {
      throw new Error(`substituteCronPlaceholders: option "${name}" must be a non-blank string`)
    }
  }

  let urls = 0
  let secrets = 0

  const out = sql
    .replace(URL_RE, () => {
      urls += 1
      return `https://${ref}.supabase.co`
    })
    .replace(SECRET_RE, (_match, prefix) => {
      secrets += 1
      return `${prefix}'${cronSecret}'`
    })

  // A silent no-op would leave the caller believing cron was rebuilt when it was not.
  if (urls === 0 && secrets === 0) {
    throw new Error('substituteCronPlaceholders: made zero substitutions')
  }

  return { sql: out, urls, secrets }
}

module.exports = {
  PROD_REF,
  DEV_REF,
  AUTH_EXCLUDE_TABLES,
  CACHE_TABLES,
  SECRET_TABLES,
  dataExcludeTables,
  snapshotDirName,
  parseSnapshotDirName,
  buildManifest,
  verifyManifest,
  assertDestructiveTargetAllowed,
  cronRowsToPlan,
  substituteCronPlaceholders,
}
