// GENERATED by scripts/sync-edge-engine.cjs from src/types/models.ts — do not edit.
// Change the source, then run `npm run sync:edge-engine`.
/** Shared data model: aligned with Supabase schema (sources/supabase/schema.sql)*/

export type Market = 'TPE' | 'US'
export type TxType = 'BUY' | 'SELL' | 'DIVIDEND' | 'STOCK_DIVIDEND'
/**
 * Trading nature of a Taiwan-market transaction (task 137 §C).
 * `DAY_TRADE` (現股當沖) halves the securities transaction tax; `SHORT` (融券) changes
 * the ledger path (see `computeLedger`), it is not a label-only value. The other two do
 * not change any calculation and are carried so a CSV round-trip does not lose the label.
 */
export type TxNature = 'SPOT' | 'DAY_TRADE' | 'MARGIN' | 'SHORT'
export type Currency = 'TWD' | 'USD'

/**
 * How the broker hands back a fee discount (2026-09-26 redesign). `monthly` (月退) brokers
 * charge the full statutory rate at settlement and refund the difference the next month (玉山,
 * 永豐 per their own pages), so their apps keep the list-price buy fee in cost (Task 189);
 * `instant` (現折 / 日退) brokers charge the discounted rate at settlement. Which rate the app
 * withholds on a sell is a separate fact, `SellFeeBasis`. Null / missing reads as `instant`.
 */
export type FeeRebate = 'instant' | 'monthly'

/**
 * Which rate the broker app withholds as the sell fee on Taiwan unrealized P&L (Task 189): `list`
 * is the posted 0.1425% (玉山 and 元大 both, measured), `net` the workspace's discounted rate.
 * Null / missing keeps the pre-Task-189 rule — `monthly` with a discount reads as `list` — so a
 * workspace that was reconciled before this field existed does not move.
 */
export type SellFeeBasis = 'list' | 'net'

/**
 * How the broker floors the estimated sell fee and tax on unrealized P&L (BUG-088). `lot`: each
 * open lot is floored on its own (玉山, the behaviour since Task 136); `position`: the whole
 * position is floored once (元大). Null / missing reads as `lot`.
 */
export type FeeRounding = 'lot' | 'position'

/**
 * One segment of a workspace's fee-rate history (Task 182): `rate` applies to a trade made on
 * `from` ('YYYY-MM-DD') or later, until the next segment starts. A broker can renegotiate the
 * discount from a given date, and a trade made before it was charged the old rate for good.
 * See `utils/feeRateHistory.ts` for the lookup and the normalisation rules.
 */
export interface FeeRateSegment {
  from: string
  rate: number
}

export interface Workspace {
  id: string
  name: string
  created_at: string
  /**
   * The rate that applied **before** the first `fee_rate_history` segment — and, when there is no
   * history, the workspace's only rate. It is never rewritten when a new discount starts, so a
   * client or an Edge Function that has not seen `fee_rate_history` still reads a real rate.
   */
  fee_rate?: number | null
  /** Ascending by `from`; see `FeeRateSegment`. Absent/null means the rate never changed. */
  fee_rate_history?: FeeRateSegment[] | null
  fee_rebate?: FeeRebate | null
  fee_rounding?: FeeRounding | null
  sell_fee_basis?: SellFeeBasis | null
  /**
   * BUG-090: does this broker estimate a lot bought *today* at the halved 現股當沖 tax?
   * 玉山 does (that is what BUG-087 measured); RON does not — its app withheld the full 0.3% on a
   * position opened the same morning. Null means "not set" and keeps the BUG-087 behaviour, so a
   * workspace that was reconciled against 玉山 does not move when this column arrives.
   */
  day_trade_tax_estimate?: boolean | null
}

export interface Transaction {
  /**
   * The order the app was told about this trade, assigned by the database on insert
   * (Task 186 / BUG-089). It is what breaks a same-day tie that `tx_date` and `created_at`
   * cannot: a bulk import writes one `created_at` for every row, and without this the engine
   * falls back to "opening legs first" and replays 買 → 賣 → 買 as 買、買、賣.
   * Absent on a database that has not run that part of schema.sql, and on hand-built test rows.
   */
  seq?: number | null
  id: string
  workspace_id: string
  /** Transaction date, format YYYY-MM-DD*/
  tx_date: string
  market: Market
  /** Stock code without 'TPE:' prefix (e.g. '2330', 'AAPL')*/
  ticker: string
  name: string
  tx_type: TxType
  price: number
  qty: number
  fee_tax: number
  /**
   * Optional like `Workspace.fee_rate`: rows written before the column existed, and PROD
   * before its migration runs, carry no value. Absent means "unknown", not 現股 —
   * the ledger then falls back to inferring the nature from `fee_tax`.
   */
  tx_nature?: TxNature | null
  /**
   * Optional handling fee rate for this transaction. Absent/null for rows written before the column
   * existed. When editing legacy rows, the UI infers or preserves the rate.
   */
  fee_rate?: number | null
  created_at: string
}

/** Transactions not yet written to the database (no id/created_at/workspace_id)*/
export type NewTransaction = Omit<Transaction, 'id' | 'created_at' | 'workspace_id'>

export function marketCurrency(market: Market): Currency {
  return market === 'TPE' ? 'TWD' : 'USD'
}

/** The only key for individual stocks in ledger: market + code (the code spaces for Taiwan and the United States are different, so composite keys are still used to prevent collisions)*/
export function positionKey(market: Market, ticker: string): string {
  return `${market}:${ticker}`
}

export const TX_TYPE_LABEL: Record<TxType, string> = {
  BUY: '買入',
  SELL: '賣出',
  DIVIDEND: '現金股利',
  STOCK_DIVIDEND: '股票股利',
}

export const TX_NATURE_LABEL: Record<TxNature, string> = {
  SPOT: '現股',
  DAY_TRADE: '當沖',
  MARGIN: '融資',
  SHORT: '融券',
}

export const MARKET_LABEL: Record<Market, string> = {
  TPE: '台股',
  US: '美股',
}
